export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'

export const LOAD_CART = 'LOAD_CART'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_ALL_PRODUCTS = 'REMOVE_ALL_PRODUCTS'
export const CHECKOUT_ADD = 'CHECKOUT_ADD'

export const UPDATE_CART = 'UPDATE_CART'
